version: 2.1
orbs:
  chiubaka: chiubaka/circleci-orb@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

test-parameters: &test-parameters
  init-submodules: true
  app-dir: ~/project/samples/generated-typescript-package
  yarn-berry: true
  nx-affected: false

filters: &filters
  tags:
    only: /.*/

jobs:
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-tests:
    executor: chiubaka/docker-node
    steps:
      # Run your orb's commands to validate them.
      - chiubaka/setup:
          <<: *test-parameters

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - chiubaka/lint:
          name: chiubaka-lint-job
          <<: *test-parameters
          filters: *filters
      - chiubaka/build:
          name: chiubaka-build-job
          <<: *test-parameters
          filters: *filters
      - chiubaka/test:
          name: chiubaka-test-job
          <<: *test-parameters
          filters: *filters
      - chiubaka/publish:
          name: chiubaka-publish-job
          context: npm-publishing
          dry-run: true
          <<: *test-parameters
          filters: *filters
      - command-tests:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: chiubaka/circleci-orb
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - chiubaka-lint-job
            - chiubaka-build-job
            - chiubaka-test-job
            - chiubaka-publish-job
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
