version: 2.1
orbs:
  chiubaka: chiubaka/circleci-orb@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

test-parameters:
  generated-typescript-package: &generated-typescript-package-test-parameters
    init-submodules: true
    app-dir: ~/project/samples/generated-typescript-package
    yarn-berry: true
    nx-affected: false
  genesis: &genesis-test-parameters
    init-submodules: true
    app-dir: ~/project/samples/genesis
    yarn-berry: true

filters: &filters
  tags:
    only: /.*/

jobs:
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-tests:
    executor: chiubaka/docker-node
    steps:
      # Run your orb's commands to validate them.
      - chiubaka/setup:
          <<: *generated-typescript-package-test-parameters
      - chiubaka/setup:
          <<: *genesis-test-parameters
      - chiubaka/compose-docker:
          app-dir: ~/project/samples/genesis
          wait-for-services:
            - chiubaka/wait-for-docker-service:
                container-name: genesis_registry
                url: http://localhost:4873/healthcheck

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - chiubaka/lint:
          name: chiubaka-lint-job
          <<: *generated-typescript-package-test-parameters
          filters: *filters
      - chiubaka/build:
          name: chiubaka-build-job
          <<: *generated-typescript-package-test-parameters
          filters: *filters
      - chiubaka/test:
          name: generated-typescript-package-test
          <<: *generated-typescript-package-test-parameters
          configure-git-user: true
          monorepo: false
          filters: *filters
      - chiubaka/test:
          name: genesis-test
          <<: *genesis-test-parameters
          configure-git-user: true
          filters: *filters
      - chiubaka/deploy:
          name: chiubaka-deploy-job
          context: npm-publishing
          dry-run: true
          <<: *generated-typescript-package-test-parameters
          configure-git-user: true
          git-user-name: Daniel Chiu
          git-user-email: daniel@chiubaka.com
          monorepo: false
          task-name: Publish to NPM
          filters: *filters
      - command-tests:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: chiubaka/circleci-orb
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - chiubaka-lint-job
            - chiubaka-build-job
            - generated-typescript-package-test
            - genesis-test
            - chiubaka-deploy-job
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
