version: 2.1
orbs:
  chiubaka: chiubaka/circleci-orb@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

test-parameters:
  generated-typescript-package: &generated-typescript-package-test-parameters
    init-submodules: true
    app-dir: ~/project/samples/generated-typescript-package
    yarn-berry: true
    nx-affected: false
  genesis: &genesis-test-parameters
    init-submodules: true
    app-dir: ~/project/samples/genesis
    yarn-berry: true
  setup-and-cleanup: &setup-and-cleanup-test-parameters
    setup-steps:
      - run:
          name: "Test custom setup step"
          command: echo "Hello, world!"
    cleanup-steps:
      - run:
          name: "Test custom cleanup step"
          command: echo "Goodbye, world!"

filters: &filters
  tags:
    only: /.*/

jobs:
  android-command-tests:
    executor: chiubaka/android
    steps:
      - chiubaka/setup-android:
          with-emulator: true
          platform-version: android-34
          << : *genesis-test-parameters
  macos-command-tests:
    executor:
      name: chiubaka/macos
      xcode-version: 14.3.1
    steps:
      - chiubaka/setup-macos:
          with-simulator: true
          simulator-device: iPhone 14
          simulator-version: 16.4
  command-tests:
    executor: chiubaka/docker-node
    steps:
      - chiubaka/setup:
          <<: *generated-typescript-package-test-parameters
      - chiubaka/setup:
          <<: *genesis-test-parameters

workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - chiubaka/lint:
          name: chiubaka-lint-job
          <<: *generated-typescript-package-test-parameters
          <<: *setup-and-cleanup-test-parameters
          filters: *filters
      - chiubaka/build:
          name: chiubaka-build-job
          <<: *generated-typescript-package-test-parameters
          <<: *setup-and-cleanup-test-parameters
          filters: *filters
      - chiubaka/test:
          name: generated-typescript-package-test
          <<: *generated-typescript-package-test-parameters
          <<: *setup-and-cleanup-test-parameters
          configure-git-user: true
          monorepo: false
          filters: *filters
      # Requires https://github.com/chiubaka/circleci-orb/issues/45 to uncomment
      # - chiubaka/test:
      #     name: genesis-test
      #     executor: chiubaka/machine
      #     <<: *genesis-test-parameters
      #     configure-git-user: true
      #     docker-compose: true
      #     wait-for-docker-services:
      #       - chiubaka/wait-for-docker-service:
      #           container-name: genesis_registry
      #           url: http://localhost:4873/healthcheck
      #     filters: *filters
      - chiubaka/deploy:
          name: chiubaka-deploy-job
          context: npm-publishing
          dry-run: true
          <<: *generated-typescript-package-test-parameters
          <<: *setup-and-cleanup-test-parameters
          configure-git-user: true
          git-user-name: CircleCI
          git-user-email: circleci@chiubaka.com
          monorepo: false
          task-name: Publish to NPM
          filters: *filters
      - command-tests:
          filters: *filters
      - android-command-tests:
          filters: *filters
      - macos-command-tests:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: chiubaka/circleci-orb
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - chiubaka-lint-job
            - chiubaka-build-job
            - generated-typescript-package-test
            - chiubaka-deploy-job
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
