description: >
  Installs and runs docker-compose in the project directory. Useful for testing support.

parameters:
  wait-for-services:
    type: steps
    default: []
    description: Runs a set of steps to wait until all required docker services are up and running

steps:
  - docker/install-docker
  - docker/install-docker-compose
  - setup_remote_docker
  - run:
      name: Build images of services declared in docker-compose.yml
      command: docker-compose build
  - run:
      name: Start all services declared in docker-compose.yml
      command: docker-compose up -d
  - steps: << parameters.wait-for-services >>
