description: >
  Builds the project code using the build script provided by package.json

executor: docker-node

parameters:
  init-submodules:
    type: boolean
    default: false
    description: Whether or not to initialize submodules included in this repository.
  app-dir:
    type: string
    default: "."
    description: Path to the directory containing your package.json file. Not needed if package.json lives in the root.
  yarn-berry:
    type: boolean
    default: false
    description: Whether or not to use Yarn berry for package management. Defaults to Yarn v1.
  nx-affected:
    type: boolean
    default: true
    description: Whether or not to set up environment variables for `nx affected`.

steps:
  - setup:
      init-submodules: << parameters.init-submodules >>
      app-dir: << parameters.app-dir >>
      yarn-berry: << parameters.yarn-berry >>
      nx-affected: << parameters.nx-affected >>
  - run:
      name: Build code
      working_directory: << parameters.app-dir >>
      command: yarn run build:ci
